--- 
name: production-core
director_uuid: DIRECTOR_UUID
release: 
  name: appcloud
  version: latest
compilation: 
  workers: 10
  network: default
  reuse_compilation_vms: true
  cloud_properties: 
    instance_type: m1.medium
update: 
  canaries: 1
  canary_watch_time: 30000-150000
  update_watch_time: 30000-150000
  max_in_flight: 4
  max_errors: 1
networks: 
- name: default
  type: dynamic
  cloud_properties: 
    security_groups: 
    - cloudfoundry-production
- name: vip_network
  type: vip
  cloud_properties: 
    security_groups: 
    - cloudfoundry-production
resource_pools: 
- name: core
  network: default
  size: 1
  stemcell: 
    name: bosh-stemcell
    version: 0.7.0
  cloud_properties: 
    instance_type: m1.small
  persistent_disk: 16192
jobs: 
- name: core
  template: 
  - postgres
  - nats
  - router
  - health_manager_next
  - cloud_controller
  - debian_nfs_server
  - serialization_data_server
  - stager
  - uaa
  - vcap_redis
  - dea
  instances: 1
  resource_pool: core
  networks: 
  - name: default
    default: 
    - dns
    - gateway
  - name: vip_network
    static_ips: 
    - 1.2.3.4
  persistent_disk: 16192
properties: 
  domain: mycompany.com
  env: 
  networks: 
    apps: default
    management: default
  router: 
    client_inactivity_timeout: 600
    app_inactivity_timeout: 600
    local_route: 1.2.3.4
    status: 
      port: 8080
      user: router
      password: c1oudc0wc1oudc0w
  nats: 
    user: nats
    password: c1oudc0wc1oudc0w
    address: 1.2.3.4
    port: 4222
  db: ccdb
  ccdb: 
    template: postgres
    address: 1.2.3.4
    port: 2544
    databases: 
    - tag: cc
      name: appcloud
    - tag: uaa
      name: uaa
    roles: 
    - name: root
      password: c1oudc0wc1oudc0w
      tag: admin
    - name: uaa
      password: c1oudc0wc1oudc0w
      tag: uaa
  cc: 
    description: Cloud Foundry
    srv_api_uri: http://api.mycompany.com
    password: c1oudc0wc1oudc0w
    token: TOKEN
    allow_debug: true
    allow_registration: true
    admins: 
    - drnic@starkandwayne.com
    admin_account_capacity: 
      memory: 2048
      app_uris: 32
      services: 16
      apps: 16
    default_account_capacity: 
      memory: 2048
      app_uris: 32
      services: 16
      apps: 16
    new_stager_percent: 100
    staging_upload_user: vcap
    staging_upload_password: c1oudc0wc1oudc0w
    uaa: 
      enabled: true
      resource_id: cloud_controller
      token_creation_email_filter: 
      - ""
    service_extension: 
      service_lifecycle: 
        max_upload_size: 5
    use_nginx: false
  postgresql_server: 
    max_connections: 30
    listen_address: 0.0.0.0
  serialization_data_server: 
    upload_token: TOKEN
    use_nginx: false
    upload_timeout: 10
    port: 8090
    upload_file_expire_time: 600
    purge_expired_interval: 30
  service_lifecycle: 
    download_url: 1.2.3.4
    mount_point: /var/vcap/service_lifecycle
    tmp_dir: /var/vcap/service_lifecycle/tmp_dir
    resque: 
      host: 1.2.3.4
      port: 3456
      password: c1oudc0wc1oudc0w
    nfs_server: 
      address: 1.2.3.4
      export_dir: /cfsnapshot
    serialization_data_server: 
    - 1.2.3.4
  stager: 
    max_staging_duration: 120
    max_active_tasks: 20
    queues: 
    - staging
  uaa: 
    cc: 
      token_secret: TOKEN_SECRET
      client_secret: CLIENT_SECRET
    admin: 
      client_secret: CLIENT_SECRET
    login: 
      client_secret: CLIENT_SECRET
    batch: 
      username: uaa
      password: c1oudc0wc1oudc0w
    port: 8100
    catalina_opts: -Xmx128m -Xms30m -XX:MaxPermSize=128m
    no_ssl: true
  uaadb: 
    address: 1.2.3.4
    port: 2544
    roles: 
    - tag: admin
      name: uaa
      password: c1oudc0wc1oudc0w
    databases: 
    - tag: uaa
      name: uaa
  vcap_redis: 
    address: 1.2.3.4
    port: 3456
    password: c1oudc0wc1oudc0w
    maxmemory: 500000000
  service_plans: {}

  dea: 
    max_memory: 512
